### ISSUE TITLE
Can't change character size

### ISSUE THREAD

**Issue by Celmar97** [OliverJPost/HumGen3D#106]
**Describe the bug**
When I try to change the height of a character, no modification is made and the UI cursor returns to the initial height, namely 163 cm. Also I have no idea if it's related but I get this error when browsing the character menu : 
`Report: Error
Python: Traceback (most recent call last):
File "/Users/gibiermarcel/Library/Application Support/Blender/4.0/scripts/addons/HumGen3D_user_interface/operators.py", line 37, in invoke
return self.execute(context)
File "/Users/gibiermarcel/Library/Application Support/Blender/4.0/scripts/addons/HumGen3D_user_interface/operators.py", line 44, in execute
hg_callback(self)
File "/Users/gibiermarcel/Library/Application Support/Blender/4.0/scripts/addons/HumGen3D/backend/callback.py", line 90, in hg_callback
_set_shader_switches(human, sett)
File "/Users/gibiermarcel/Library/Application Support/Blender/4.0/scripts/addons/HumGen3D/backend/callback.py", line 108, in _set_shader_switches
"off" if principled_bsdf.inputs["Subsurface"].default_value == 0 else "on"
KeyError: 'bpy_prop_collection[key]: key "Subsurface" not found'
`
**To Reproduce**
With the same environment do : 
- Install the add-on
- Install content packs 
- Create a character and change its size

**Screenshots**

https://github.com/OliverJPost/HumGen3D/assets/38401841/d2033854-9e6e-4cfd-9005-37709b99d942

**Desktop (please complete the following information):**
 - OS: [MacOS Ventura 13.4]
 - Blender Version [4.0.2]
 - Human Generator Version [4.0.14]

**Comment by OliverJPost** [comment]
The error message you describe has been fixed in versions of HG after v4.0.14, please see https://help.humgen3d.com/update

Could you check if this update also fixes the height change for you?
