### ISSUE TITLE
i have bug to use humangen3 : it gives me this error when click to generate new human

### ISSUE THREAD

**Issue by adirus121** [OliverJPost/HumGen3D#117]
Python: Traceback (most recent call last):
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\human\operators.py", line 36, in execute
    human = Human.from_preset(sett.pcoll.humans, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\decorators.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\decorators.py", line 119, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\human\human.py", line 194, in from_preset
    set_eevee_ao_and_strip(context)
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\render.py", line 15, in set_eevee_ao_and_strip
    context.scene.render.engine = "BLENDER_EEVEE"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "BLENDER_EEVEE" not found in ('BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', 'CYCLES')

**Comment by kllthgvrnmnt** [comment]
I have the same problem. Blender 4.2.1 LTS

**Comment by kllthgvrnmnt** [comment]
Oh I found thw answer, you have to update generator. https://help.humgen3d.com/update

**Comment by OliverJPost** [comment]
This issue was indeed resolved in v4.0.20
