### ISSUE TITLE
Can't Add Object As New Footwear

### ISSUE THREAD

**Issue by paulxwilkinson** [OliverJPost/HumGen3D#118]
**Describe the bug**
Whenever I try to new footwear using the "Add object as clothing" button it fails with the following error:

Error: Python: Traceback (most recent call last):
  File "/Users/paulwilkinson/Library/Application Support/Blender/4.2/scripts/addons/HumGen3D/backend/content/saving_operators.py", line 274, in execute
    self.human.clothing.footwear.add_obj(
  File "/Users/paulwilkinson/Library/Application Support/Blender/4.2/scripts/addons/HumGen3D/common/decorators.py", line 119, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulwilkinson/Library/Application Support/Blender/4.2/scripts/addons/HumGen3D/human/clothing/footwear.py", line 59, in add_obj
    super().add_obj(cloth_obj, "footwear", recalculate_weights, context)
  File "/Users/paulwilkinson/Library/Application Support/Blender/4.2/scripts/addons/HumGen3D/human/clothing/base_clothing.py", line 154, in add_obj
    _add_corrective_shapekeys(cloth_obj, self._human, cloth_type)
  File "/Users/paulwilkinson/Library/Application Support/Blender/4.2/scripts/addons/HumGen3D/human/clothing/add_obj_to_clothing.py", line 60, in _add_corrective_shapekeys
    corrective_shapekey_names = sk_name_dict[cloth_type]
                                ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'footwear'

Everything works fine when I'm adding other types of clothing - tops, trousers etc. - so it only seems to fail when I'm adding footwear.  

Caveat: I can't find detailed instructions anywhere for footwear so i may be doing something wrong, but i have tried single objects, mirrored objects etc. and always the same error.

Any ideas?

Apologies if I'm doing something wrong!

OS: Mac Sonoma 14.3.1
Blender 4.2.1
HG version: 4.0.21

THANK YOU!

**Comment by OliverJPost** [comment]
I think this issue is due to the auto updater of Human Generator not correctly updating the `json` file where `footwear` was previously called `shoes`.

I've renamed the file to hopefully force it to update it correctly, this will be included in the next update in the upcoming days
