### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Mugdin12** [OliverJPost/HumGen3D#122]
I have mistake after the first attempt to generate new human. 
Python: Traceback (most recent call last):
  File "C:\Users\mugdi\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\human\operators.py", line 36, in execute
    human = Human.from_preset(sett.pcoll.humans, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mugdi\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\decorators.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mugdi\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\decorators.py", line 119, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mugdi\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\human\human.py", line 194, in from_preset
    set_eevee_ao_and_strip(context)
  File "C:\Users\mugdi\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\render.py", line 15, in set_eevee_ao_and_strip
    context.scene.render.engine = "BLENDER_EEVEE"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "BLENDER_EEVEE" not found in ('BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', 'CYCLES')

**Comment by Mugdin12** [comment]
I solved the problem after updating the human generator
