### ISSUE TITLE
Python error when starting batch mode "Create Humans"

### ISSUE THREAD

**Issue by senorSimonsen** [OliverJPost/HumGen3D#27]
**Describe the bug**
When I add some Human markers, and try to click the "Generate X humans" button, I get a Python error (see screenshot).

**To Reproduce**
1. Go to the batch menu
2. Click on 'Generate X humans'
3. See error

**Error**
Error: Python: Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\HumGen3D\features\batch_section\HG_BATCH_MODAL_OPERATOR.py", line 171, in modal
    expressions_category = self._choose_category_list(context, 'expressions'),
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\HumGen3D\features\batch_section\HG_BATCH_MODAL_OPERATOR.py", line 227, in _choose_category_list
    bpy.ops.hg3d.refresh_batch_uilists()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\HumGen3D\user_interface\HG_BATCH_UILIST.py", line 136, in execute
    batch_uilist_refresh(self, context, 'outfits')
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\HumGen3D\user_interface\HG_BATCH_UILIST.py", line 96, in batch_uilist_refresh
    found_folders_male = find_folders(self, context, categ, gender, include_all = False, gender_override= 'male')
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\HumGen3D\core\settings\HG_PROP_FUNCTIONS.py", line 49, in find_folders
    dirlist = os.listdir(categ_folder)
FileNotFoundError: [WinError 3] Den angivne sti blev ikke fundet: 'C:\\Users\\USERNAME\\OneDrive\\3D\\HumanGeneratorAssetPacks\\outfits\\male'
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version 3.3.0
 - Human Generator Version 3.0.4

**Comment by senorSimonsen** [comment]
Hi. I changed the settings to point to another folder, and moved the content packs there. That seemed to fix the error message. thanks!
