### ISSUE TITLE
Clicking Random Choice Gives Python Error

### ISSUE THREAD

**Issue by radman-x** [OliverJPost/HumGen3D#39]
**Describe the bug**
Clicking the HG random choice button gives Python error.

**To Reproduce**
1. Open Blender v3.4.0. Delete default cube.
2. Open HG v4 (beta 1) via vertical add-on tab
3. Click Random Choice icon
4. See Python Error:
 
Read prefs: C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Reloading external rigs...
Reloading external metarigs...
HG_INFO:         Activating HumGen, version (4, 0, 1)
Info: Deleted 1 object(s)

HG_INFO:         <FrameSummary file C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\randomize_operators.py, line 42 in execute>
HG_WARNING:      Argument 'context' for function 'get_preset_options' substituted with bpy.context.  It's highly recommended to pass your own context!
Traceback (most recent call last):
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\randomize_operators.py", line 42, in execute
    options = Human.get_preset_options(sett.gender, context)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\decorators.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\human.py", line 90, in get_preset_options
    preview_collections["humans"].populate(context, gender, subcategory=category)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\backend\preview_collections.py", line 130, in populate
    pcoll_full_dir = os.path.join(
  File "H:\Program Files\Blender Foundation\3.4\python\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "H:\Program Files\Blender Foundation\3.4\python\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'Context'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\randomize_operators.py", line 42, in execute
    options = Human.get_preset_options(sett.gender, context)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\decorators.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\human.py", line 90, in get_preset_options
    preview_collections["humans"].populate(context, gender, subcategory=category)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\backend\preview_collections.py", line 130, in populate
    pcoll_full_dir = os.path.join(
  File "H:\Program Files\Blender Foundation\3.4\python\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "H:\Program Files\Blender Foundation\3.4\python\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'Context'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version v3.4.0
 - Human Generator Version v4Beta1

**Comment by OliverJPost** [comment]
I thought this was fixed in beta 4, I will verify this. Thanks for the report!

**Comment by radman-x** [comment]
This still occurs in v4.beta.6.
