### ISSUE TITLE
Generating Human (Asian1) Gives Python Error with Blender 3.4.0 and HG v4

### ISSUE THREAD

**Issue by radman-x** [OliverJPost/HumGen3D#40]
**Describe the bug**
Generating Human (Asian1) Gives Python Error with Blender 3.4.0 and HG v4, though it still seems to work.

**To Reproduce**
1. Open Blender v3.4.0. Delete default cube.
2. Open HG v4 (beta 1) via vertical add-on tab
3. Choose Asian1 from asset browser (note: even though the asset browser button says "Male", it really opens females; in order to get to Asian1 male, must click on "Female", then back on "Male".
4. Click "Generate New Human".
5. See Python Error (note that even though this error is displayed, a human is generated):

Info: Deleted 1 object(s)

addon_utils.disable: HumGen3D not disabled
Modules Installed (HumGen3D) from 'F:\\Installers\\HumanGenerator_Blender_Install_Files\\HumGen3D_V4_0_1_BETA.zip' into 'C:\\Users\\Bruce A. Rady\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\backend\content\content_packs.py", line 472, in cpacks_refresh
    dirlist = os.listdir(json_folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\Blender3Data\\HumanGeneratorFiles\\\\content_packs'
File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\backend\content\content_packs.py", line 457, in cpacks_refresh
Traceback (most recent call last):
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\backend\content\content_packs.py", line 472, in cpacks_refresh
    dirlist = os.listdir(json_folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\Blender3Data\\HumanGeneratorFiles\\\\content_packs'
File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\backend\content\content_packs.py", line 457, in cpacks_refresh
Writing userprefs: 'C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend' ok
Info: Preferences saved
HG_INFO:         Starting unzip, file: <module 'zipfile' from 'H:\\Program Files\\Blender Foundation\\3.4\\python\\lib\\zipfile.py'>
HG_INFO:         Starting unzip, file: <module 'zipfile' from 'H:\\Program Files\\Blender Foundation\\3.4\\python\\lib\\zipfile.py'>
HG_INFO:         Starting unzip, file: <module 'zipfile' from 'H:\\Program Files\\Blender Foundation\\3.4\\python\\lib\\zipfile.py'>
HG_INFO:         Starting unzip, file: <module 'zipfile' from 'H:\\Program Files\\Blender Foundation\\3.4\\python\\lib\\zipfile.py'>
Traceback (most recent call last):
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\operators.py", line 36, in execute
    human = Human.from_preset(sett.pcoll.humans, context)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\decorators.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\human.py", line 219, in from_preset
    occurred_errors = getattr(human, attr).set_from_dict(data)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\age.py", line 116, in set_from_dict
    self.set(data["set"])
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\age.py", line 88, in set
    node_age_color.inputs["Fac"].default_value = age_key_value
KeyError: 'bpy_prop_collection[key]: key "Fac" not found'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\operators.py", line 36, in execute
    human = Human.from_preset(sett.pcoll.humans, context)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\common\decorators.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\human.py", line 219, in from_preset
    occurred_errors = getattr(human, attr).set_from_dict(data)
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\age.py", line 116, in set_from_dict
    self.set(data["set"])
  File "C:\Users\Bruce A. Rady\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\HumGen3D\human\age.py", line 88, in set
    node_age_color.inputs["Fac"].default_value = age_key_value
KeyError: 'bpy_prop_collection[key]: key "Fac" not found'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version v3.4.0
 - Human Generator Version v4Beta1

**Comment by radman-x** [comment]
At this point, decided to start rolling back from Blender v3.4 and HG v4. Will report in this issue whether these errors still exist in other combinations.

**Comment by radman-x** [comment]
Blender v3.3.2 and HG v3 work better -- this error does not appear.

**Comment by radman-x** [comment]
Error occurs with Blender v3.4 and HG v3.

**Comment by OliverJPost** [comment]
Seems to be an incompatibility of HGV4 and Blender 3.4, will fix in next release

**Comment by radman-x** [comment]
Now fixed with HG v4.beta.6.
