### ISSUE TITLE
Python Error when trying the Batch Generator

### ISSUE THREAD

**Issue by petruganj** [OliverJPost/HumGen3D#42]
**Describe the bug**
A clear and concise description of what the bug is. If you get an error message, please copy-paste it or add a screenshot of it.

**To Reproduce**
1. Create Human generator marker
2. Click on batch generator, generate 1 human
3. See error

**Screenshots**

Python: Traceback (most recent call last):
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\batch_generator\operators.py", line 163, in invoke
    return self.execute(context)
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\batch_generator\operators.py", line 202, in execute
    self._generate_human_for_marker(context, marker)
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\batch_generator\operators.py", line 218, in _generate_human_for_marker
    human = self.generator.generate_human(context, pose_type)
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\common\decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\batch_generator\generator.py", line 71, in generate_human
    human = Human.from_preset(chosen_preset, from_batch_generator=True)
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\common\decorators.py", line 44, in wrapper
    raise_if_pytest_human(args)
  File "C:\Users\Petru Ganj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\HumGen3D\common\decorators.py", line 22, in raise_if_pytest_human
    if "pytest_human" in human._rig_obj:
AttributeError: type object 'Human' has no attribute '_rig_obj'

**Desktop :**
 - OS: Windows 10
 - Blender Version 3.2.0
 - Human Generator Version 4.0.0

**Comment by OliverJPost** [comment]
Fixed the issue, this fix will be included in the next beta release

**Comment by petruganj** [comment]
When is the next beta release?
