### ISSUE TITLE
"bpy_struct "ProcessProps" registration error" when enabling V4 plugin

### ISSUE THREAD

**Issue by rbregier** [OliverJPost/HumGen3D#43]
Hello,
I can install the HumGen3D V4 plugin in Blender but when I try to enable it I get this error:
```
Exception in module register(): /home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/__init__.py
Traceback (most recent call last):
  File "/home/rbregier/Workspace/Humans/BlenderHumansRenderings/blender-3.3.3-linux-x64/3.3/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/__init__.py", line 146, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "ProcessProps" registration error: 'baking' PointerProperty could not register (see previous error)
```

Do you have an idea of what could be the problem?

**To Reproduce**
1. Go to Edit / Preferences / Add-ons / Install: provide path to HumGen3D_V4_0_6_BETA.zip and install it.
2. Tick the 'Enable Add-on' button for Human Generator 3D.
3. See the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1822210/215793068-de3dcf8b-f439-46e0-b4e4-0c1f57c6855e.png)

**Desktop:**
 - OS: Ubuntu 22.04
 - Blender Version 3.3.3 (I tried with Blender 3.4 and faced the same issue).
 - Human Generator Version 4.0.6. I tried with the latest version from the main branch and faced the same issue. I can enable the V3 plug-in however.

**Comment by OliverJPost** [comment]
The error message indicates it failed to register, but the error that caused this is not included. Could you run Blender from the terminal (so you can see the output log inside the terminal), reproduce the error and send a copy of the full log?

**Comment by rbregier** [comment]
Thank you very much for the reply,
Here is the full console log I get when I try to activate the module on a fresh Blender 3.3.3.

```
> ./blender --version
Blender 3.3.3
	build date: 2023-01-17
	build time: 09:10:16
	build commit date: 2023-01-17
	build commit time: 08:40
	build hash: 8d94aeb604fa
	build platform: Linux
	build type: release
	build c flags:  -Wall -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -D_GLIBCXX_USE_CXX11_ABI=0  
	build c++ flags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -D_GLIBCXX_USE_CXX11_ABI=0  
	build link flags:  -Wl,--version-script='/home/blender/git/blender-v330/blender.git/source/creator/symbols_unix.map'
	build system: CMake

> ./blender

Read prefs: /home/rbregier/.config/blender/3.3/config/userpref.blend
../src/intel/isl/isl.c:2220: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.

> Installation of HumGen3D_V4_0_6_BETA.zip: nothing special to report

addon_utils.disable: HumGen3D not disabled
Modules Installed (HumGen3D) from '/home/rbregier/Documents/Humans/Human Generator/Human Generator v3/HumGen3D_V4_0_6_BETA.zip' into '/home/rbregier/.config/blender/3.3/scripts/addons'

> Activation of the module: I get this error message in console:

TypeError: PointerProperty(...) expected an RNA type, failed with: RuntimeError: , missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)

Exception in module register(): /home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/__init__.py
Traceback (most recent call last):
  File "/home/rbregier/Workspace/Humans/blenderhumangenerator/blender-3.3.3-linux-x64/3.3/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/__init__.py", line 146, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "ProcessProps" registration error: 'baking' PointerProperty could not register (see previous error)

Traceback (most recent call last):
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/user_interface/process_panel/process_panel.py", line 47, in poll
    if not super().poll(context):
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/user_interface/ui_baseclasses.py", line 69, in poll
    human_is_legacy = is_legacy(context.object)
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/object_finding.py", line 17, in is_legacy
    rig_obj = find_hg_rig(obj, include_legacy=True)
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/object_finding.py", line 57, in find_hg_rig
    if obj and obj.HG.ishuman:
AttributeError: 'Object' object has no attribute 'HG'
Traceback (most recent call last):
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/user_interface/content_panel/content_panel.py", line 28, in poll
    if not super().poll(context):
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/user_interface/ui_baseclasses.py", line 69, in poll
    human_is_legacy = is_legacy(context.object)
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/object_finding.py", line 17, in is_legacy
    rig_obj = find_hg_rig(obj, include_legacy=True)
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/object_finding.py", line 57, in find_hg_rig
    if obj and obj.HG.ishuman:
AttributeError: 'Object' object has no attribute 'HG'
Traceback (most recent call last):
  File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/user_interface/batch_panel/batch_panel.py", line 33, in poll
    sett = context.scene.HG3D  # type:ignore[attr-defined]
AttributeError: 'Scene' object has no attribute 'HG3D'

```

**Comment by rbregier** [comment]
Hi,
I may have found a solution. Changing the _register_priority value to 3 here seems to fix the activation issue:
https://github.com/OliverJPost/HumGen3D/blob/5732ba8aad356d06c06fb11d5768fd2a170f24fb/backend/properties/bake_props.py#L42

Should I expect some downside effects?

**Comment by OliverJPost** [comment]
Thanks for the clear report! Fixed the issue and will be included in next update
