### ISSUE TITLE
Broken handling of Blender context

### ISSUE THREAD

**Issue by rbregier** [OliverJPost/HumGen3D#45]
Hi,

Could you please fix the way you deal with Blender context in this add-on?
API is unusable because of this.

**To Reproduce**
```python
from HumGen3D import Human
```
When I provide context, I can generate a human but I receive warnings that the context is not provided:
```python
context = bpy.context
human_options = Human.get_preset_options(gender="male", context=context)
my_human = Human.from_preset(chosen_option, context=context)
# HG_INFO:    [0m <FrameSummary file /home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
# [93mHG_WARNING:    [0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
```

When I don't provide context, I get errors:
```python
human_options = Human.get_preset_options(gender="male")
# Traceback (most recent call last):
#   File "<blender_console>", line 1, in <module>
#   File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/decorators.py", line 44, in wrapper
#     raise_if_pytest_human(args)
#   File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/decorators.py", line 17, in raise_if_pytest_human
#     self = args[0]
# IndexError: tuple index out of range

Human.from_preset(chosen_option)
# Traceback (most recent call last):
#   File "<blender_console>", line 1, in <module>
#   File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/decorators.py", line 44, in wrapper
#     raise_if_pytest_human(args)
#   File "/home/rbregier/.config/blender/3.3/scripts/addons/HumGen3D/common/decorators.py", line 22, in raise_if_pytest_human
#     if "pytest_human" in human._rig_obj:
# AttributeError: type object 'Human' has no attribute '_rig_obj'
```

I could circumvent this bug by always providing context, but context is not always forwarded properly.
For example the BatchHumanGenerator is unusable (at least) because the context input is not passed to this function:
https://github.com/OliverJPost/HumGen3D/blob/8b0c0105add787cfea6c95ad0693c94e4f09a98c/batch_generator/generator.py#L60

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Blender Version 3.3.3
 - Human Generator Version 4.0.6

**Comment by OliverJPost** [comment]
Thanks for the report. This issue has been fixed in main and will be released with the next beta update
