### ISSUE TITLE
ModuleNotFoundError: No module named 'HumGen3D'

### ISSUE THREAD

**Issue by gerroon** [OliverJPost/HumGen3D#98]
I get this error when I enable the addon. I do not see to have any issue with Humgen3

Windows 11, Humgen 4.0.14 Windows

```
Traceback (most recent call last):
  File "c:\blender-4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "c:\blender-4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HumGen3D_v4\__init__.py", line 43, in <module>
    from .backend.auto_classes import _get_bpy_classes
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HumGen3D_v4\backend\__init__.py", line 4, in <module>
    from .logging import hg_log
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HumGen3D_v4\backend\logging.py", line 6, in <module>
    from .preferences import get_prefs
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HumGen3D_v4\backend\preferences\__init__.py", line 4, in <module>
    from .preference_func import get_addon_root, get_prefs  # noqa
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HumGen3D_v4\backend\preferences\preference_func.py", line 8, in <module>
    import HumGen3D
ModuleNotFoundError: No module named 'HumGen3D'
```

**Comment by HG3D** [comment]
Probably you downloaded the code directly from GitHub and it was installed as a zip called something else than HumGen3D.zip internally. Please download from GitHub releases or from BlenderMarket
Regards,

Oliver

**Comment by gerroon** [comment]
I downloaded it from Blender market

This is the content of the unzipped folder

![image](https://github.com/OliverJPost/HumGen3D/assets/8519469/2d28ceb3-88a7-478d-9c2c-06a3b9562ab4)

**Comment by gerroon** [comment]
It seems like it had something to do with the junction points on Windows. I was using junctions to symlink the folder.
